
theme: jekyll-theme-modernist
title: "ETH0 Academy"
description: "Training, Service, and IT Support"

show_downloads: true

github:
  blog_url: https://eth-nol.com/blog/
  owner_name: https://github.com/eth-nol

include: ['.well-known/acme-challenge']
keep_files: ['.well-known/acme-challenge']

url: https://eth-nol.com
enforce_ssl: true
