
theme: jekyll-theme-modernist
title: "ETH0 Academy"
description: "Training, Service, and IT Support"

show_downloads: true
is_project_page: true

github:
  blog_url: https://eth-nol.com/blog/
  owner_name: eth-nol

include: ['/.well-known/acme-challenge/']
keep_files: [/.well-known/acme-challenge/, 9RZl4ofyWA6RYIYhUzpzwPCtozgTp5FNb6SR_i8qw-s, JhURzCgXrbK7I-vaXaB4D9A7zp-FrKjkZaTLBeyckbM]

url: https://eth-nol.com
enforce_ssl: true
