
theme: jekyll-theme-modernist
title: "ETH0 Academy"
description: "Training, Service, and IT Support"
keep_files: [
  '.well-known/acme-challenge'
]
site: https://eth-nol.com

url: https://eth-nol.com
enforce_ssl: eth-nol.com
